[colors]
foreground= "{color1}"
background= "{color13}"
cursor_bg= "{color1}"
cursor_fg= "black"
cursor_border= "{color2}"
selection_fg= "black"
selection_bg= "{color7}"
scrollbar_thumb= "{color3}"
split= "{color4}"
ansi= ["{color0}", "{color1}", "{color2}", "{color3}", "{color4}", "{color5}", "{color6}", "{color7}",]
brights= ["{color8}", "{color9}", "{color10}", "{color11}", "{color12}", "{color13}", "{color14}", "{color15}",]
